# For a description of these parameters, please visit the theme wiki.
# https://github.com/pacollins/hugo-future-imperfect-slim/wiki/config.toml
baseurl                 = "https://aestears.github.io/"
DefaultContentLanguage  = "en"
title                   = "Alice Stears"
theme                   = "hugo-future-imperfect-slim"
paginate                = 3
disqusShortname         = ""
googleAnalytics         = ""
pluralizeListTitles     = false
disableLanguages        = []

[markup.goldmark.renderer]
  unsafe                = true

[outputs]
  home                  = ["html", "json", "rss"]

[params]
  enableCDN             = false
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = ""
  highlightjsLang       = []
  viewMorePostsLink     = "/blog/"
  readingTime           = true
  imageStretch          = ""
  removeBlur            = false
  socialShare           = ["twitter", "facebook", "reddit", "linkedin", "pinterest", "email"]
  hideEmptyStats        = false

  [params.meta]
    description         = "A theme by HTML5 UP, ported by Julio Pescador. Slimmed and enhanced by Patrick Collins. Multilingual by StatnMap. Powered by Hugo."
    author              = "HTML5UP and Hugo"
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [params.header]
    navbarTitle         = "Future Imperfect"
    dynamicTitles       = true
    searchMenu          = true
    shareMenu           = true
    languageMenu        = true

  [params.intro]
    header                = "Hugo Future Imperfect Slim"
    paragraph             = "Another fine, responsive site template by <a href='http://html5up.net'>HTML5 UP</a>."
    rssIntro              = true
    socialIntro           = true
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false

    [params.intro.pic]
      src                 = "img/main/logo.jpg"
      shape               = "circle"
      width               = ""
      alt                 = "Hugo Future Imperfect Slim"

  [params.sidebar]
    about               = "This theme was developed for Hugo static site generator."
    postAmount          = 5
    categories          = true
    categoriesByCount   = true

  [params.footer]
    rssFooter           = true
    socialFooter        = true

  [params.staticman]
    enabled             = true
    api                 = ""  # No Trailing Slash
    gitProvider         = ""
    username            = ""
    repo                = ""
    branch              = ""

    [params.staticman.recaptcha]
      siteKey           = ""
      encryptedKey      = ""

[menu]

  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = "/"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1

  [[menu.main]]
    name              = "About"
    identifier        = "about"
    url               = "/about/"
    pre               = "<i class='far fa-id-card'></i>"
    weight            = 2

  [[menu.main]]
    name              = "Blog"
    identifier        = "blog"
    url               = "/blog/"
    pre               = "<i class='far fa-newspaper'></i>"
    weight            = 3

  [[menu.main]]
    name              = "Categories"
    identifier        = "categories"
    url               = "/categories/"
    pre               = "<i class='fas fa-sitemap'></i>"
    weight            = 5

  [[menu.main]]
    name              = "Contact"
    identifier        = "contact"
    url               = "/contact/"
    pre               = "<i class='far fa-envelope'></i>"
    weight            = 6

[Languages]

  [Languages.en]
    LanguageCode        = "en"
    LanguageName        = "English"
    weight              = 1


[social]
  # Coding Communities
  github                = "aestears"
  #gitlab                = ""
  #stackoverflow         = "" # User Number
  #bitbucket             = ""
  #jsfiddle              = ""
  #codepen               = ""
  # Visual Art Communities
  #deviantart            = ""
  #flickr                = "example"
  #behance               = ""
  #dribbble              = ""
  # Publishing Communities
  #wordpress             = ""
  #medium                = ""
  # Professional/Business Oriented Communities
  linkedin              = "alice-stears-153415b9"
  #linkedin_company      = "examplebusiness"
  #foursquare            = ""
  #xing                  = ""
  #slideshare            = ""
  # Social Networks
  #facebook              = "example"
  #googleplus            = ""
  #reddit                = "example"
  #quora                 = ""
  #youtube               = ""
  #vimeo                 = ""
  #whatsapp              = "" # WhatsApp Number
    # WeChat and QQ need testing.
    #wechat              = ""
    #qq                  = "" # User ID Number
  #instagram             = "example"
  #tumblr                = ""
  twitter               = "alice_stears"
  #strava                = ""
  #skype                 = ""
  #snapchat              = ""
  #pinterest             = "example"
  #telegram              = "example"
  #vine                  = ""
  #googlescholar         = ""
  orcid                 = "0000-0002-1325-6641"
  researchgate          = "Alice-Stears"
  #keybase               = "example"
  #mastodon              = "example.com/@example"
  # Email
  email                 = "astears@uwyo.edu"
